// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Models;

[Table("indicators")]
[Index("MeasurUnitId", Name = "IX_indicators_measur_unit_id")]
[Index("YearTypeId", Name = "IX_indicators_year_type_id")]
public partial class Indicator
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Column("notes")]
    public string Notes { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Column("measur_unit_id")]
    public long? MeasurUnitId { get; set; }

    [Column("main_source")]
    public string MainSource { get; set; }

    [Column("year_type_id")]
    public long YearTypeId { get; set; }

    [InverseProperty("Indicator")]
    public virtual ICollection<IndicatorTranslation> IndicatorTranslations { get; set; } = new List<IndicatorTranslation>();

    [InverseProperty("Indicator")]
    public virtual ICollection<PublicationIndicator> PublicationIndicators { get; set; } = new List<PublicationIndicator>();
}