// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Models;

[Table("periodics")]
[Index("Name", Name = "IX_periodics_name", IsUnique = true)]
public partial class Periodic
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [InverseProperty("Periodic")]
    public virtual ICollection<PeriodicTranslation> PeriodicTranslations { get; set; } = new List<PeriodicTranslation>();

    [InverseProperty("Periodic")]
    public virtual ICollection<Publication> Publications { get; set; } = new List<Publication>();
}