// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Models;

[Table("publication_type_translations")]
[Index("PublicationTypeId", "Locale", Name = "IX_publication_type_translations_publication_type_id_locale", IsUnique = true)]
public partial class PublicationTypeTranslation
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Required]
    [Column("locale")]
    [StringLength(6)]
    public string Locale { get; set; }

    [Column("publication_type_id")]
    public long PublicationTypeId { get; set; }

    [ForeignKey("PublicationTypeId")]
    [InverseProperty("PublicationTypeTranslations")]
    public virtual PublicationType PublicationType { get; set; }
}