// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Models;

[Table("publications")]
[Index("Name", Name = "IX_publications_name", IsUnique = true)]
[Index("PeriodicId", Name = "IX_publications_periodic_id")]
[Index("PublicAdministrationId", Name = "IX_publications_public_administration_id")]
[Index("PublicationTypeId", Name = "IX_publications_publication_type_id")]
[Index("SubsubjectId", Name = "IX_publications_subsubject_id")]
[Index("YearTypeId", Name = "IX_publications_year_type_id")]
public partial class Publication
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("periodic_id")]
    public long PeriodicId { get; set; }

    [Column("publication_type_id")]
    public long PublicationTypeId { get; set; }

    [Column("public_administration_id")]
    public long PublicAdministrationId { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Column("subsubject_id")]
    public long SubsubjectId { get; set; }

    [Column("year_type_id")]
    public long YearTypeId { get; set; }

    [Column("publish_date")]
    public DateTime? PublishDate { get; set; }

    [ForeignKey("PeriodicId")]
    [InverseProperty("Publications")]
    public virtual Periodic Periodic { get; set; }

    [InverseProperty("Publication")]
    public virtual ICollection<PublicationDetail> PublicationDetails { get; set; } = new List<PublicationDetail>();

    [InverseProperty("Publication")]
    public virtual ICollection<PublicationTag> PublicationTags { get; set; } = new List<PublicationTag>();

    [InverseProperty("Publication")]
    public virtual ICollection<PublicationTranslation> PublicationTranslations { get; set; } = new List<PublicationTranslation>();

    [ForeignKey("PublicationTypeId")]
    [InverseProperty("Publications")]
    public virtual PublicationType PublicationType { get; set; }

    [ForeignKey("SubsubjectId")]
    [InverseProperty("Publications")]
    public virtual Subject Subsubject { get; set; }
}