// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Models;

[Table("subjects")]
[Index("MainSubjectId", Name = "IX_subjects_main_subject_id")]
public partial class Subject
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("title")]
    public string Title { get; set; }

    [Column("main_subject_id")]
    public long? MainSubjectId { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Required]
    [Column("is_system")]
    public bool? IsSystem { get; set; }

    [InverseProperty("MainSubject")]
    public virtual ICollection<Subject> InverseMainSubject { get; set; } = new List<Subject>();

    [ForeignKey("MainSubjectId")]
    [InverseProperty("InverseMainSubject")]
    public virtual Subject MainSubject { get; set; }

    [InverseProperty("SubSubject")]
    public virtual ICollection<News> News { get; set; } = new List<News>();

    [InverseProperty("Subsubject")]
    public virtual ICollection<Publication> Publications { get; set; } = new List<Publication>();

    [InverseProperty("Subject")]
    public virtual ICollection<SubjectTranslation> SubjectTranslations { get; set; } = new List<SubjectTranslation>();
}